// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function GetBoilerData() {
  return window['go']['main']['App']['GetBoilerData']();
}

export function IsModbusConnected() {
  return window['go']['main']['App']['IsModbusConnected']();
}
