// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function PLC_DATA():Promise<Array<main.BoilerData>>;

export function SaveConfig(arg1:main.Config):Promise<void>;
