// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<string>;

export function GetBoilerData():Promise<Array<main.BoilerData>>;

export function IsModbusConnected():Promise<boolean>;
